[package]
name = "spark-connect-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.9.2"

[build-dependencies]
protoc-gen-tonic = "0.2.2"
tonic = "0.9.2"
tonic-build = "0.9.2"
